# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95ffd74aa1553577add456943a67cd0fc56212c8831e9fd225e3d23a1781d9b019ed52ccef3b4fd03d3d5b81ad9651a0c33ac5b94fb6da3b26caf0e0b8c456f8

test:
  secret_key_base: 77a480dce493085134716323be5ee7a812fdb3beb30b9404096385c0341a8d80e9b3c64dd2ac7ac13c4a37f114d41d100ed8a4c3cea511bd8edb1fe26d246379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
